Change travis config as workaround, setuptools breaking builds
Setuptools breaks the travis build;
`AttributeError: 'Distribution' object has no attribute 'install_requires'`

Attempting workaround as suggested in this (otherwise unrelated) commit:
https://github.com/pythonnet/pythonnet/pull/524/commits/6d0fc9a6231ac9861b4091e251012a3908fb723c